<?xml version="1.0" encoding="utf-8"?><Database Name="recipesdb" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Data\recipesdb.mdf;Initial Catalog=RecipeAssignment;Integrated Security=True;Connect Timeout=30" SettingsObjectName="RecipeAssignment.Properties.Settings" SettingsPropertyName="recipesdbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Recipes" Member="Recipes">
    <Type Name="Recipe">
      <Column Name="recipe_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="recipe_name" Type="System.String" DbType="NChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="cooking_time" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="is_favorite" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ingredients" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>