#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeAssignment.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="recipesdb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRecipe(Recipe instance);
    partial void UpdateRecipe(Recipe instance);
    partial void DeleteRecipe(Recipe instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::RecipeAssignment.Properties.Settings.Default.recipesdbConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Recipe> Recipes
		{
			get
			{
				return this.GetTable<Recipe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recipes")]
	public partial class Recipe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _recipe_id;
		
		private string _recipe_name;
		
		private string _description;
		
		private System.TimeSpan _cooking_time;
		
		private bool _is_favorite;
		
		private string _ingredients;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrecipe_idChanging(int value);
    partial void Onrecipe_idChanged();
    partial void Onrecipe_nameChanging(string value);
    partial void Onrecipe_nameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Oncooking_timeChanging(System.TimeSpan value);
    partial void Oncooking_timeChanged();
    partial void Onis_favoriteChanging(bool value);
    partial void Onis_favoriteChanged();
    partial void OningredientsChanging(string value);
    partial void OningredientsChanged();
    #endregion
		
		public Recipe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recipe_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int recipe_id
		{
			get
			{
				return this._recipe_id;
			}
			set
			{
				if ((this._recipe_id != value))
				{
					this.Onrecipe_idChanging(value);
					this.SendPropertyChanging();
					this._recipe_id = value;
					this.SendPropertyChanged("recipe_id");
					this.Onrecipe_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recipe_name", DbType="NChar(200) NOT NULL", CanBeNull=false)]
		public string recipe_name
		{
			get
			{
				return this._recipe_name;
			}
			set
			{
				if ((this._recipe_name != value))
				{
					this.Onrecipe_nameChanging(value);
					this.SendPropertyChanging();
					this._recipe_name = value;
					this.SendPropertyChanged("recipe_name");
					this.Onrecipe_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cooking_time", DbType="Time NOT NULL")]
		public System.TimeSpan cooking_time
		{
			get
			{
				return this._cooking_time;
			}
			set
			{
				if ((this._cooking_time != value))
				{
					this.Oncooking_timeChanging(value);
					this.SendPropertyChanging();
					this._cooking_time = value;
					this.SendPropertyChanged("cooking_time");
					this.Oncooking_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_favorite", DbType="Bit NOT NULL")]
		public bool is_favorite
		{
			get
			{
				return this._is_favorite;
			}
			set
			{
				if ((this._is_favorite != value))
				{
					this.Onis_favoriteChanging(value);
					this.SendPropertyChanging();
					this._is_favorite = value;
					this.SendPropertyChanged("is_favorite");
					this.Onis_favoriteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingredients", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string ingredients
		{
			get
			{
				return this._ingredients;
			}
			set
			{
				if ((this._ingredients != value))
				{
					this.OningredientsChanging(value);
					this.SendPropertyChanging();
					this._ingredients = value;
					this.SendPropertyChanged("ingredients");
					this.OningredientsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
